/**
 * Session-layer error types.
 *
 * Fixed codes, no inheritance games, no cleverness.
 */

export type SessionErrorCode =
  | "SESSION_NOT_FOUND"
  | "DOD_MISSING"
  | "LOCK_MISSING"
  | "LOCK_NOT_APPROVED"
  | "GATE_FAILED"
  | "SCHEMA_INVALID"
  | "ID_MISMATCH"
  | "MODE_VIOLATION"
  | "EXECUTION_PLAN_LINT_FAILED"
  | "EVIDENCE_VALIDATION_FAILED"
  | "REVIEWER_FAILED"
  | "REVIEWER_DUPLICATE"
  | "STEP_ENVELOPE_INVALID"
  | "PATCH_ARTIFACT_INVALID"
  | "EVIDENCE_REQUIRED"
  | "PLAN_HASH_MISSING"
  | "PLAN_HASH_MISMATCH"
  | "EVIDENCE_CHAIN_INVALID"
  | "ANCHOR_INVALID"
  | "SESSION_BOUNDARY_INVALID"
  | "RUNNER_IDENTITY_INVALID"
  | "ATTESTATION_INVALID"
  | "ATTESTATION_SIGNATURE_INVALID"
  | "POLICY_INVALID"
  | "POLICY_EVALUATION_FAILED"
  | "POLICY_FIELD_PATH_INVALID"
  | "POLICY_OPERATOR_UNSUPPORTED"
  | "POLICY_DENIED"
  | "POLICY_REQUIREMENT_FAILED"
  | "REPLAY_HASH_MISMATCH"
  | "REPLAY_VALIDATION_FAILED"
  | "REPLAY_BUNDLE_INVALID"
  | "REPLAY_NON_DETERMINISTIC"
  | "PROMPT_CAPSULE_INVALID"
  | "PROMPT_CAPSULE_LINT_FAILED"
  | "MODEL_RESPONSE_INVALID"
  | "MODEL_RESPONSE_LINT_FAILED"
  | "CAPSULE_HASH_MISMATCH"
  | "RESPONSE_HASH_MISMATCH"
  | "BOUNDARY_VIOLATION"
  | "FORBIDDEN_TOKEN_DETECTED"
  | "IMPORT_BOUNDARY_VIOLATION"
  | "SYMBOL_INDEX_INVALID"
  | "SYMBOL_VALIDATION_FAILED"
  | "SYMBOL_RESOLUTION_FAILED"
  | "SYMBOL_EXPORT_VIOLATION"
  | "REPO_SNAPSHOT_INVALID"
  | "SNAPSHOT_HASH_MISSING"
  | "SNAPSHOT_HASH_MISMATCH"
  | "PATCH_APPLY_FAILED"
  | "PATCH_BASE_MISMATCH";

export class SessionError extends Error {
  public readonly code: SessionErrorCode;
  public readonly details: Record<string, unknown>;

  constructor(
    message: string,
    code: SessionErrorCode,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "SessionError";
    this.code = code;
    this.details = details ?? {};
  }
}
